### ISSUE TITLE
Editable CAD file?

### ISSUE THREAD

**Issue by junnikokuki** [roydenwa/robotics_practical#13]
Hi,
I want to make a backpack for my NAO, and due to the out of stock of the the power bank, I need to modify the 3d print part to fit my power bank. The stl file is not modifiable, can you provide an editable format of the 3d print part? Thank you.

**Comment by roydenwa** [comment]
Hi, happy to hear that. Unfortunately, I don't have the CAD files on my PC anymore. But, they are based on the nao-backpack model and they provide step files at: https://github.com/uchile-robotics/nao-backpack/tree/master/backpack_cad
So, maybe you can recreate it with that.

**Comment by junnikokuki** [comment]
Okey, Thanks.
